spring:
  resources:
    add-mappings: true
    static-locations:
      - /home/tvingadmin/ffmpeg/out/
  thymeleaf:
    cache: false    
    check-template: false
    check-template-location: false
    prefix: /views/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    content-type: text/html;charset=UTF-8    
  activemq:
    broker-url: tcp://119.149.188.226:61616
    user: admin
    password: admin
  redis:
    host: 119.149.188.226
    port: 6379   
    

      